# Generated by Django 4.2 on 2023-11-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('HSN_Code', models.IntegerField()),
                ('Cost_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Selling_Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
