# Generated by Django 4.2 on 2023-11-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='HSN_Code',
            field=models.IntegerField(unique=True),
        ),
    ]
